import { motion } from 'framer-motion';
import { CheckCircle, RotateCcw, Download, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';

export default function SettleUpButton({ expenses, onSettle, onReset }) {
  const handleExport = () => {
    if (expenses.length === 0) {
      toast.error('No expenses to export 📋');
      return;
    }

    const total = expenses.reduce((s, e) => s + e.amount, 0);
    const people = {};
    expenses.forEach((e) => {
      people[e.name] = (people[e.name] || 0) + e.amount;
    });
    const names = Object.keys(people);
    const perPerson = total / names.length;

    // Calculate settlements
    const balances = {};
    names.forEach((n) => {
      balances[n] = people[n] - perPerson;
    });

    const settlements = [];
    const debtors = [];
    const creditors = [];

    Object.entries(balances).forEach(([name, bal]) => {
      if (bal < -0.01) debtors.push({ name, amount: Math.abs(bal) });
      else if (bal > 0.01) creditors.push({ name, amount: bal });
    });

    debtors.sort((a, b) => b.amount - a.amount);
    creditors.sort((a, b) => b.amount - a.amount);

    let di = 0, ci = 0;
    while (di < debtors.length && ci < creditors.length) {
      const pay = Math.min(debtors[di].amount, creditors[ci].amount);
      if (pay > 0.01) {
        settlements.push({ from: debtors[di].name, to: creditors[ci].name, amount: pay });
      }
      debtors[di].amount -= pay;
      creditors[ci].amount -= pay;
      if (debtors[di].amount < 0.01) di++;
      if (creditors[ci].amount < 0.01) ci++;
    }

    let text = `═══════════════════════════════════\n`;
    text += `  Split Mitra – Expense Report ✨\n`;
    text += `  ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}\n`;
    text += `═══════════════════════════════════\n\n`;
    text += `📊 SUMMARY\n`;
    text += `  Total Spent: ₹${total.toFixed(2)}\n`;
    text += `  People: ${names.length}\n`;
    text += `  Per Head: ₹${perPerson.toFixed(2)}\n\n`;
    text += `💸 EXPENSES\n`;
    expenses.forEach((e) => {
      text += `  • ${e.name}: ₹${e.amount.toFixed(2)} (${e.reason || 'General'})\n`;
    });
    text += `\n🤝 SETTLEMENTS\n`;
    if (settlements.length === 0) {
      text += `  Everyone is settled up! 🎉\n`;
    } else {
      settlements.forEach((s) => {
        text += `  • ${s.from} → ${s.to}: ₹${s.amount.toFixed(2)}\n`;
      });
    }
    text += `\n═══════════════════════════════════\n`;
    text += `  Generated by Split Mitra ❤️☕\n`;
    text += `═══════════════════════════════════\n`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `split-mitra-report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report exported! 📥');
  };

  return (
    <motion.div
      className="glass-card"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.4 }}
    >
      <h2 className="section-title">
        <div
          className="w-8 h-8 rounded-lg flex items-center justify-center"
          style={{
            background: 'rgba(16,185,129,0.15)',
            border: '1px solid rgba(16,185,129,0.25)',
          }}
        >
          <CheckCircle size={16} style={{ color: '#10b981' }} />
        </div>
        <span>Actions</span>
      </h2>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
        {/* Settle Up */}
        <motion.button
          className="btn-success py-3 flex items-center justify-center gap-2 text-sm"
          onClick={() => {
            if (expenses.length === 0) {
              toast.error('No expenses to settle 📋');
              return;
            }
            onSettle();
            toast.success('Settled up! History saved 🎉');
          }}
          whileHover={{ scale: 1.03, boxShadow: '0 8px 25px rgba(16,185,129,0.3)' }}
          whileTap={{ scale: 0.97 }}
        >
          <CheckCircle size={16} />
          Settle Up
        </motion.button>

        {/* Export */}
        <motion.button
          className="btn-secondary py-3 flex items-center justify-center gap-2 text-sm"
          onClick={handleExport}
          whileHover={{ scale: 1.03 }}
          whileTap={{ scale: 0.97 }}
        >
          <Download size={16} />
          Export
        </motion.button>

        {/* Reset */}
        <motion.button
          className="btn-danger py-3 flex items-center justify-center gap-2 text-sm"
          onClick={() => {
            if (expenses.length === 0) {
              toast.error('Nothing to reset 📋');
              return;
            }
            onReset();
            toast.success('All expenses cleared! 🔄');
          }}
          whileHover={{ scale: 1.03 }}
          whileTap={{ scale: 0.97 }}
        >
          <Trash2 size={16} />
          Clear All
        </motion.button>
      </div>
    </motion.div>
  );
}
